services:
  # Backend API
  - type: web
    name: uni-pool-api
    runtime: node
    repo: https://github.com/ndlokesh/uni-pool
    branch: main
    plan: free
    region: singapore
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://ndlokesh14_db_user:3NuX008xMzYQOpjO@unipool.8v6vlzz.mongodb.net/uni-pool?appName=unipool
      - key: JWT_SECRET
        value: UNI_POOL_SECRET_KEY_123

staticSites:
  # Frontend Web App
  - name: uni-pool-web
    repo: https://github.com/ndlokesh/uni-pool
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://uni-pool-api.onrender.com/api
      - key: REACT_APP_GOOGLE_MAPS_API_KEY
        value: AIzaSyCmeqXzQgQgIsxxE-kBHv2jPnn9tF134AM
